version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - "C:/Users/ADMIN/Desktop/my-backend-project/:/my-backend/my-backend-project"
    environment:
      - "PORT=5000"
    links:
      - mongo

    depends_on:
      - mongo
    command: ["npm", "start"]
    restart: on-failure

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "C:/mongodb/db:/data/db"
